name: CrazyWeather
main: de.st_ddt.crazyweather.CrazyWeather
author: ST-DDT
#C*=needed core version
version: C3_2
softdepend: [PermissionsBukkit]
depend: [CrazyCore]
commands:
  weather:
    description: Change the weather
    usage: /<command> sun|/<command> rain|/<command> storm
  sun:
    description: Cast sun
    usage: /<command>
  rain:
    description: Cast rain
    usage: /<command>|/<command> date|/<command> date time
  storm:
    description: Cast thunderstorm
    usage: /<command>
  thunder:
    description: Cast a lighting strike on target.
    usage: /<command>|/<command> player
  thundertool:
    description: Shows/Sets the current thundertool
    usage: /<command>|/<command> ToolID
permissions:
  crazyweather.*:
    description: Access to all commands
    default: false
    children:
      crazyweather.change.*: true
      crazyweather.set.*: true
      crazyweather.thunder: true
      crazyweather.thunder.player: true
      crazyweather.thunder.tool: true
      crazyweather.thunder.toolchange: true
  crazyweather.change.*:
    description: Access to all commands for changing weather
    default: op
    children:
      crazyweather.change.sun: true
      crazyweather.change.rain: true
      crazyweather.change.thunder: true
  crazyweather.set.*:
    description: Access to all commands for freezing weather
    default: op
    children:
      crazyweather.change.*: true
      crazyweather.set.sun: true
      crazyweather.set.rain: true
      crazyweather.set.thunder: true
  crazyweather.change.sun: 
    description: Allow changing the current weather to sunny
    default: op
  crazyweather.change.rain: 
    description: Allow changing the current weather to rain
    default: op
  crazyweather.change.thunder: 
    description: Allow changing the current weather to thunderstorm
    default: op
  crazyweather.set.sun: 
    description: Allow freezing the weather to sunny
    default: op
    children:
      crazyweather.change.sun: true
  crazyweather.set.rain: 
    description: Allow freezing the weather to rain
    default: op
    children:
      crazyweather.change.rain: true
  crazyweather.set.thunder: 
    description: Allow freezing the weather to thunderstorm
    default: op
    children:
      crazyweather.change.thunder: true
  crazyweather.thunder: 
    description: Allow casting thunderstrikes
    default: op
  crazyweather.thunder.tool: 
    description: Allow casting thunderstrikes with tool
    default: false
  crazyweather.thunder.toolchange: 
    description: Allow changing thunderstrikes tool
    default: false
  crazyweather.thunder.player: 
    description: Allow casting thunderstrikes on player
    default: op