name: CrazyArenaPvE
main: de.st_ddt.crazyarena.CrazyArenaPvE
author: ST-DDT
version: 0.1
# requires CrazyCore v10.2
# requires CrazyGeo v0.3
# requires CrazyArena v0.3.1
depend: [CrazyCore,CrazyGeo,CrazyArena]
description: >
            Adds PvE (Monster) Arenas to your server.
commands:
  crazyarenapve:
    description: Plugin Main Menu.
    usage: /<command> [subcommands]
    aliases: [car]
permissions:
  crazyarenapve.*:
    description: Gives access to all crazyarenapve functions.
    default: op
    children:
      crazyarenarace.dummy: true
