name: CrazyArena
main: de.st_ddt.crazyarena.CrazyArena
author: ST-DDT
version: 0.3
# requires CrazyCore v9.7
# requires CrazyGeo v0.1
depend: [CrazyCore,CrazyGeo]
softdepend: [CrazyChats]
description: >
            CrazyArenaPlugin Core needed for all CrazyArenaPlugins.
commands:
  crazyarena:
    description: Plugin Main Menu.
    usage: /<command> [subcommands]
    aliases: [ca]
  arenajoin:
    description: Join an arena as player.
    usage: /<command> [Arena/Player]
    aliases: [ajoin,join]
  arenaspectate:
    description: Join an arena as spectator. 
    usage: /<command> [Arena/Player]
    aliases: [aspectate,spectate]
  arenajudge:
    description: Join an arena as judge. 
    usage: /<command> [Arena/Player]
    aliases: [ajudge,judge]
  arenainvite:
    description: Invite a player to your arena.
    usage: /<command> <Player.../*>
    aliases: [ainvite,invite]
  arenaready:
    description: Flag yourself as ready.
    usage: /<command>
    aliases: [aready,ready]
  arenateam:
    description: Choose a team inside your arena.
    usage: /<command> [subcommands]
    aliases: [ateam,team]
  arenaleave:
    description: Leave your arena.
    usage: /<command> [subcommands]
    aliases: [aleave,leave,aquit,quit]
permissions:
  crazyarena.*:
    description: Gives access to all crazyarena functions
    default: op
    children:
      crazyarena*.*: true
      crazyarena.use: true
      crazyarena.op: true
      crazyarena.admin: true
      crazyarena.arena: true
  crazyarena*.*:
    description: Access to all crazyarenaplugin commands
    default: false 
  crazyarena.use:
    description: Gives access to all user functions
    default: true
    children:
      crazyarena.join: true
      crazyarena.spectate: true
      crazyarena.leave: true
      crazyarena.invite: true
  crazyarena.admin:
    description: Gives access to all admin functions
    default: op
    children:
      crazyarena.invite.all: true
      crazyarena.arena.switchmode: true
      crazyarena.arena.import: true
      crazyarena.arena.create: true
      crazyarena.arena.delete: true
      crazyarena.arena.modify: true
      crazyarena.arena.sign: true
      crazyarena.forceready: true
      crazyarena.forcestop: true
      crazyarena.kick: true