name: CrazyLogin
main: de.st_ddt.crazylogin.CrazyLogin
author: ST-DDT
version: 6.5.2
# requires CrazyCore v8.5 or later
depend: [CrazyCore]
description: >
            CrazyLogin protect your server with passwords and many usefully features.
commands:
  login:
    description: Login using a password
    usage: /<command> <Password...>
  logout:
    description: Logout and leave server
    usage: /<command>
  register:
    description: Create/Change password
    usage: /<command> <new Password>
  crazylogin:
    description: Plugin Main Menu
    usage: /<command> password <new Password>
    aliases: [cl]
permissions:
  crazylogin.*:
    description: Access to all commands
    default: false
    children:
      crazylogin.admin: true
      crazylogin.mode: true
      crazylogin.ensureregistration: true
      crazylogin.warnloginfailure: true
      crazylogin.warncommandexploits: true
      crazylogin.warndatabase: true
      crazylogin.warndelete: true
      crazylogin.warnsession: true
      crazylogin.register: true
      crazylogin.list: true
      crazylogin.commands: true
      crazylogin.dropOldData: true
      crazylogin.player.info: true
      crazylogin.player.info.self: true
      crazylogin.player.info.other: true
      crazylogin.player.create: true
      crazylogin.player.delete: true
      crazylogin.list: true
  crazylogin.admin:
    description: Allow changing account data for other players
    default: op
    children: 
      crazylogin.mode: true
      crazylogin.ensureregistration: true
      crazylogin.warnloginfailure: true
      crazylogin.warncommandexploits: true
      crazylogin.warndatabase: true
      crazylogin.warndelete: true
      crazylogin.warnsession: true
      crazylogin.register: true
      crazylogin.commands: true
      crazylogin.list: true
      crazylogin.dropOldData: true
      crazylogin.player.info: true
      crazylogin.player.info.self: true
      crazylogin.player.info.other: true
      crazylogin.player.create: true
      crazylogin.player.delete: true
  crazylogin.ensureregistration:
    description: This player can always register an account
    default: op
  crazylogin.register:
    description: Allow players to create a password. (for external registration)
    default: true
  crazylogin.warnloginfailure:
    description: Get informed if someone fails to login
    default: op
  crazylogin.warncommandexploits:
    description: Get informed if someone tries to execute a none whitelisted command.
    default: op
  crazylogin.warndatabase:
    description: Get informed if database connection fails
    default: op
  crazylogin.warnalgorithm:
    description: Get informed if no algorithm is set.
    default: op
  crazylogin.warnsession:
    description: Get informed if somebody tries to login from another location.
    default: op
  crazylogin.warndelete:
    description: Get informed if old accounts are deleted (via admincommands)
    default: op
  crazylogin.mode:
    description: Allow changing plugin mode
    default: op
  crazylogin.commands:
    description: Allow viewing and editing command whitelist.
    default: op
  crazylogin.list:
    description: List all player accounts.
    default: op
  crazylogin.dropOldData:
    description: Allow deleting old accounts.
    default: op
    children:
      crazylogin.warndelete: true
  crazylogin.player.info:
    description: Allow viewing playerinfo.
    default: op
    children:
      crazylogin.player.info.self: true
      crazylogin.player.info.other: true
  crazylogin.player.info.self:
    description: Allow viewing own playerinfo.
    default: true
  crazylogin.player.info.other:
    description: Allow viewing playerinfo for other players.
    default: op
  crazylogin.player.create:
    description: Allow creating player data
    default: op
  crazylogin.player.delete:
    description: Allow deleting player data
    default: op