name: CrazyLogin
main: de.st_ddt.crazylogin.CrazyLogin
author: ST-DDT
version: 7.7
# requires CrazyCore v9.7 or later
depend: [CrazyCore]
description: >
            CrazyLogin protect your server with passwords and many usefully features.
commands:
  login:
    description: Login using a password
    usage: /<command> <Password...>
    aliases: [l]
  adminlogin:
    description: Login into another account using an admin account.
    usage: /<command> <Admin> <AdminPassword...>
  logout:
    description: Logout and leave server
    usage: /<command>
  register:
    description: Create/Change password
    usage: /<command> <new Password>
    aliases: [changepw,chgpw,changepassword]
  crazylogin:
    description: Plugin Main Menu
    usage: /<command> password <new Password>
    aliases: [cl]
permissions:
  crazylogin.*:
    description: Access to all commands
    default: false
    children:
      crazylogin.admin: true
      crazylogin.mode: true
      crazylogin.ensureregistration: true
      crazylogin.warnloginfailure: true
      crazylogin.warncommandexploits: true
      crazylogin.warndatabase: true
      crazylogin.warndelete: true
      crazylogin.warnsession: true
      crazylogin.register.command: true
      crazylogin.register.channel: true
      crazylogin.login.command: true
      crazylogin.login.channel: true
      crazylogin.adminlogin: true
      crazylogin.requirepassword: true
      crazylogin.logout.command: true
      crazylogin.logout.channel: true
      crazylogin.commands: true
      crazylogin.dropolddata: true
      crazylogin.player.info: true
      crazylogin.player.info.self: true
      crazylogin.player.info.other: true
      crazylogin.player.create: true
      crazylogin.player.password: true
      crazylogin.player.delete: true
      crazylogin.player.list: true
  crazylogin.admin:
    description: Allow changing account data for other players
    default: op
    children: 
      crazylogin.mode: true
      crazylogin.ensureregistration: true
      crazylogin.warnloginfailure: true
      crazylogin.warncommandexploits: true
      crazylogin.warndatabase: true
      crazylogin.warndelete: true
      crazylogin.warnsession: true
      crazylogin.register.command: true
      crazylogin.register.channel: true
      crazylogin.login.command: true
      crazylogin.login.channel: true
      crazylogin.adminlogin: true
      crazylogin.requirepassword: true
      crazylogin.logout.command: true
      crazylogin.logout.channel: true
      crazylogin.commands: true
      crazylogin.dropolddata: true
      crazylogin.player.info: true
      crazylogin.player.info.self: true
      crazylogin.player.info.other: true
      crazylogin.player.create: true
      crazylogin.player.password: true
      crazylogin.player.delete: true
      crazylogin.player.list: true
  crazylogin.ensureregistration:
    description: This player can always register an account.
    default: op
    children: 
      crazylogin.register.command: true
      crazylogin.register.channel: true
  crazylogin.register:
    description: Allow players to create a password. (Depreciated)
    default: true
    children: 
      crazylogin.register.command: true
      crazylogin.register.channel: true
  crazylogin.register.command:
    description: Allow players to create a password via command.
    default: true
  crazylogin.register.channel:
    description: Allow players to create a password via pluginChannel.
    default: true
  crazylogin.login.command:
    description: Allow players to login via command.
    default: true
  crazylogin.login.channel:
    description: Allow players to login via pluginChannel.
    default: true
  crazylogin.adminlogin:
    description: Allow admins to login as another player.
    default: op
    children:
      crazylogin.requirepassword: true
  crazylogin.requirepassword: 
    description: Force this player to create a password.
    default: op
  crazylogin.blockadminlogin:
    description: Block admins logins to this account.
    default: false
  crazylogin.logout.command:
    description: Allow players to logout via command.
    default: true
  crazylogin.logout.channel:
    description: Allow players to logout via pluginChannel.
    default: true
  crazylogin.warnloginfailure:
    description: Get informed if someone fails to login
    default: op
  crazylogin.warncommandexploits:
    description: Get informed if someone tries to execute a none whitelisted command.
    default: op
  crazylogin.warndatabase:
    description: Get informed if database connection fails
    default: op
  crazylogin.warnalgorithm:
    description: Get informed if no algorithm is set.
    default: op
  crazylogin.warnsession:
    description: Get informed if somebody tries to login from another location.
    default: op
  crazylogin.warndelete:
    description: Get informed if old accounts are deleted (via admincommands)
    default: op
  crazylogin.mode:
    description: Allow changing plugin mode
    default: op
  crazylogin.commands:
    description: Allow viewing and editing command whitelist.
    default: op
  crazylogin.dropolddata:
    description: Allow deleting old accounts.
    default: op
    children:
      crazylogin.warndelete: true
  crazylogin.player.info:
    description: Allow viewing playerinfo.
    default: op
    children:
      crazylogin.player.info.self: true
      crazylogin.player.info.other: true
  crazylogin.player.info.self:
    description: Allow viewing own playerinfo.
    default: true
  crazylogin.player.info.other:
    description: Allow viewing playerinfo for other players.
    default: op
  crazylogin.player.create:
    description: Allow creating player data
    default: op
  crazylogin.player.password:
    description: Allow changing a players password
    default: op
  crazylogin.player.delete:
    description: Allow deleting player data
    default: op
  crazylogin.player.list:
    description: List all player accounts.
    default: op