name: CrazyCompass
main: de.st_ddt.crazycompass.CrazyCompass
author: ST-DDT
#C*=needed core version
version: C8_1.3
depend: [CrazyCore]
description: >
            CrazyCompass point to the center of your attention.