name: CrazyArena_PvE
main: de.st_ddt.crazyarena.CrazyArenaPvE
author: ST-DDT
version: C7_G0.1_A0.1_0.1
softdepend: [PermissionsBukkit]
depend: [CrazyCore,CrazyArena]
description: >
            PvE Arena Plugin