name: CrazyArenaSpleef
main: de.st_ddt.crazyarena.CrazyArenaSpleef
author: ST-DDT
version: C7_G0.1_A0.1_0.1
softdepend: [PermissionsBukkit]
depend: [CrazyCore,CrazyGeo,CrazyArena]
description: >
            Spleef Arena Plugin