name: CrazyPromoter
main: de.st_ddt.crazypromoter.CrazyPromoter
author: ST-DDT
#C*=needed core version
version: C8_2.9.2
depend: [CrazyCore]
softdepend: [PermissionsBukkit,PermissionsEx,GroupManager,CrazyOnline,CrazyLogin]
commands:
  promotioncheck:
    description: Check promotion status
    usage: /<command> [Player]
  crazypromoter:
    descrition: Plugin Main Menu
    usage: /<command> ...
permissions:
  crazypromoter.check:
    description: Check promotions status
    default: op
    children: 
      crazypromoter.check.self: true
      crazypromoter.check.other: true
  crazypromoter.check.self:
    description: Check your promotion status
    default: true
  crazypromoter.check.other:
    description: Check players promotion status
    default: op
