name: CrazyCommandKey
main: de.st_ddt.crazycommandkey.CrazyCommandKey
author: ST-DDT
version: 1.6.1
website: http://dev.bukkit.org/server-mods/crazycore/pages/crazy-command-key/
# requires CrazyCore v10 or later
depend: [CrazyCore]
commands:
  key:
    description: Use a key and activate command.
    usage: /<command> <Key>
    aliases: [usekey]
  genkey:
    description: Generate a key with a given command.
    usage: /<command> <Command...>
    aliases: [gkey]
  crazycommandkey:
    descrition: Plugin Main Menu
    usage: /<command> ...
    aliases: [cckey]
permissions:
  crazycommandkey.*:
    description: Access to all commands
    default: false
    children:
      crazycommandkey.keyuse: true
      crazycommandkey.keygen: true
  crazycommandkey.keyuse:
    description: Allow using a keys.
    default: true
  crazycommandkey.keygen:
    description: Allow generating keys.
    default: op
