name: CrazyFeather
main: de.st_ddt.crazyfeather.CrazyFeather
author: ST-DDT
version: 1.3
# requires CrazyCore v9 or later
depend: [CrazyCore]
description: >
            CrazyFeather collect more feathers from chickens.
permissions:
  crazyfeather.*:
    description: Access to all commands
    default: false