# CrazyOnline config.yml
# For more information visit
# https://github.com/ST-DDT/Crazy/blob/master/CrazyOnline/src/config.yml
version: X_Y
# required plugins +version can be found there
# https://github.com/ST-DDT/Crazy/blob/master/CrazyLogin/src/plugin.yml
database:
# the table/file/section name of the database
  tableName: CrazyOnline_players
# column names (does not affect FLAT databases)
  columns:
    name: name
    firstLogin: firstLogin
    lastLogin: lastLogin
    lastLogout: lastLogout
    onlineTime: onlineTime
    ip: ip
# database saveTypes can be MYSQL, FLAT and CONFIG
# additional information about MYSQL can be fould here http://dev.bukkit.org/server-mods/crazycore/pages/mys-ql/
  saveType: FLAT
# whether the database should be saved on shutdown
  saveOnShutdown: true
# show a list of players being online in the meantime when joining the server
showOnlineInfo: true
# delete players a short time after leaving the server when not online for at least 5 minutes in total
deleteShortVisitors: false
# automatically delete accounts that haven't been used for x days(-1=disabled)
# WARNING: deletes all data belonging to this player (including those saved in other plugins; equals "/crazycore delete Player")
autoDelete: -1
logs:
  Quit: false
  Join: false
