name: CrazyEnchanter
main: de.st_ddt.crazyenchanter.CrazyEnchanter
author: ST-DDT
version: 1.1.1
# requires CrazyCore v9.5 or later
depend: [CrazyCore]
description: >
            Enchant your items.
commands:
  enchant:
    description: Enchant hand held item
    usage: /<command> <Enchantment> [Level [Unsafe]]
  crazyenchanter:
    description: Plugin Mainmenu
    usage: /<command> [Subcommands...]
    aliases: [ce]
permissions:
  crazyenchanter.*:
    description: Access to all commands
    default: false
    children:
      crazyenchanter.enchant: true
  crazyenchanter.enchant:
    description: Allow enchanting your item.
    default: op