name: CrazyArenaRace
main: de.st_ddt.crazyarena.CrazyArenaRace
author: ST-DDT
version: 0.2
# requires CrazyCore v10
# requires CrazyGeo v0.3
# requires CrazyArena v0.3.1
depend: [CrazyCore,CrazyGeo,CrazyArena]
description: >
            Adds Racing Arenas to your server.
commands:
  crazyarenarace:
    description: Plugin Main Menu.
    usage: /<command> [subcommands]
    aliases: [car]
permissions:
  crazyarenarace.*:
    description: Gives access to all crazyarena functions
    default: op
    children:
      crazyarenarace.dummy: true

